version: '3.8'

services:
  backend:
    build: ./server
    container_name: backend
    ports:
      - "4040:4040"
    env_file:
      - ./server/.env
    depends_on:
      - postgres
      - minio
    networks:
      - app-network

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mann8314
      POSTGRES_DB: pkm_system
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network

volumes:
  pgdata:
  minio-data:

networks:
  app-network: